
package base;

import java.awt.Color;
import java.util.*;
import java.io.*;

public class Register extends javax.swing.JFrame {
 
    //private static boolean isStudent = false;
    //private static boolean isTutor = false;
    private static int x;
    private static int y;
    public Register() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        F_F.setBackground(new Color(0,0,0,0));
        U_F.setBackground(new Color(0,0,0,0));
        P_F.setBackground(new Color(0,0,0,0));
        jTextField1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        F_N = new javax.swing.JLabel();
        F_F = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        U_N = new javax.swing.JLabel();
        U_F = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        P_N = new javax.swing.JLabel();
        P_F = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        R_B = new javax.swing.JLabel();
        Reg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        F_N.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        F_N.setForeground(new java.awt.Color(240, 240, 240));
        F_N.setText("Full Name :");
        jPanel1.add(F_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 20));

        F_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        F_F.setForeground(new java.awt.Color(240, 240, 240));
        F_F.setToolTipText("Enter Your Full Name");
        F_F.setBorder(null);
        F_F.setOpaque(false);
        F_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_FActionPerformed(evt);
            }
        });
        jPanel1.add(F_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 290, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 290, 10));

        U_N.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        U_N.setForeground(new java.awt.Color(240, 240, 240));
        U_N.setText("User Name :");
        jPanel1.add(U_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        U_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        U_F.setForeground(new java.awt.Color(240, 240, 240));
        U_F.setToolTipText("Enter Your UserName ");
        U_F.setBorder(null);
        U_F.setOpaque(false);
        jPanel1.add(U_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 300, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 290, 10));

        P_N.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P_N.setForeground(new java.awt.Color(240, 240, 240));
        P_N.setText("Password :");
        jPanel1.add(P_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        P_F.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        P_F.setForeground(new java.awt.Color(240, 240, 240));
        P_F.setToolTipText("Enter Password");
        P_F.setBorder(null);
        P_F.setOpaque(false);
        P_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_FActionPerformed(evt);
            }
        });
        jPanel1.add(P_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 300, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 290, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student/Tutor :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 290, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 290, 10));

        R_B.setBackground(new java.awt.Color(100, 145, 217));
        R_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        R_B.setForeground(new java.awt.Color(240, 240, 240));
        R_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        R_B.setText("Register");
        R_B.setOpaque(true);
        R_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_BMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                R_BMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                R_BMouseExited(evt);
            }
        });
        jPanel1.add(R_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 100, 40));

        Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/base/Reg.jpg"))); // NOI18N
        Reg.setText("jLabel1");
        jPanel1.add(Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 380, 490));

        jLabel2.setText("jLabel2");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 380, 30));

        jRadioButton1.setText("jRadioButton1");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void R_BMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_BMouseEntered
        // TODO add your handling code here:
        R_B.setBackground(new Color(69, 95, 181));
    }//GEN-LAST:event_R_BMouseEntered

    private void R_BMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_BMouseExited
        // TODO add your handling code here:
        R_B.setBackground(new Color(100, 145, 217));
    }//GEN-LAST:event_R_BMouseExited

    private void F_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_FActionPerformed

    private void P_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_FActionPerformed

    private void R_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_BMouseClicked
        // TODO add your handling code here:
        String N = F_F.getText();
        String U = U_F.getText();
        String P = P_F.getText();
        String st = jTextField1.getText();
        Login l = new Login();
        try
        {
        FileWriter w = new FileWriter("LOGIN.txt",true);
        w.write(N + "/" + U + "/" + P + "/" + st + "\n");
        w.close();
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_R_BMouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
       int c_x = evt.getXOnScreen();
        int c_y = evt.getYOnScreen();
        
        this.setLocation(c_x - x, c_y - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F_F;
    private javax.swing.JLabel F_N;
    private javax.swing.JPasswordField P_F;
    private javax.swing.JLabel P_N;
    private javax.swing.JLabel R_B;
    private javax.swing.JLabel Reg;
    private javax.swing.JTextField U_F;
    private javax.swing.JLabel U_N;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
