/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Search extends javax.swing.JInternalFrame {

    ArrayList<Tutor> t_c = new ArrayList<>();
    ArrayList<Tutor> t_a = new ArrayList<>();
    private static String c_name;
    private static String l_name;
    private static String from;
    private static String to;
    private static String studente;
    private static String studentn;
    private static String num;
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
       // from = "";
    }
    public void catv(String name,String student_e)
    {
        studentn = name;
        studente = student_e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Search Based on Local Area :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Go");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search Based on Course :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 170, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Go");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 30, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Course 1", "Course 2", "Contact No.", "Email", "Local Area", "Full Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 760, 310));

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Send Mail");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 80, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Clear");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int f = evt.getClickCount();
        if(f==1)
        {
            c_name = jTextField2.getText();
            Table_C();
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int f = evt.getClickCount();
        if(f==1)
        {
            l_name = jTextField1.getText();
            Table_A();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         int selected = jTable1.getSelectedRow();
         to = model.getValueAt(selected, 4).toString();
         num = model.getValueAt(selected, 0).toString();
            //Mail m = new Mail();
            Mailer.send("tutorprobee@gmail.com","Apple12@bee",to,"Request Message","Hello " + num +"\n"+"You have a message from "+studentn+"\n"+"\n"+"Regards Tutorprobe");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         while(model.getRowCount()>0)
         {
             for(int i =0;i<model.getRowCount();i++)
             {
                 model.removeRow(i);
             }
         }
    }//GEN-LAST:event_jLabel6MouseClicked
  public void fillC_A(String course)
  {
      
       String line = null;
        try
        {
        FileReader fr = new FileReader("Tutor.txt");
        BufferedReader br = new BufferedReader(fr);
        while((line = br.readLine())!=null)
        {
            StringTokenizer t = new StringTokenizer(line,"/");
            while(t.hasMoreTokens())
            {
                String n = t.nextToken();
                String u = t.nextToken();
                String pw = t.nextToken();
                String d_g = t.nextToken();
                int c_n = Integer.parseInt(t.nextToken());
                String e = t.nextToken();
                String c1 = t.nextToken();
                String c2 = t.nextToken();
                String ar = t.nextToken();
                String far = t.nextToken();
                if(c1.equalsIgnoreCase(course)||c2.equalsIgnoreCase(course))
                {
                    t_c.add(new Tutor(n,u,pw,d_g,c_n,e,c1,c2,ar,far));
                }
            }
        }
        
        fr.close();
        br.close();
        }
        catch(IOException et)
                {
                   et.printStackTrace();
                }
  }
  public void Table_C()
  {
      t_c.removeAll(t_c);
      fillC_A(c_name);
      DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
      Object rowData[] = new Object[7];
      for(int i=0;i<t_c.size();i++)
      {
          rowData[0] = t_c.get(i).getN();
          rowData[1] = t_c.get(i).getC1();
          rowData[2] = t_c.get(i).getC2();
          rowData[3] = t_c.get(i).getC();
          rowData[4] = t_c.get(i).getEm();
          rowData[5] = t_c.get(i).getAd();
          rowData[6] = t_c.get(i).getFAd();
          model.addRow(rowData);
      }
  }
  public void fillL_A(String location)
  {
      
       String line = null;
        try
        {
        FileReader fr = new FileReader("Tutor.txt");
        BufferedReader br = new BufferedReader(fr);
        while((line = br.readLine())!=null)
        {
            StringTokenizer t = new StringTokenizer(line,"/");
            while(t.hasMoreTokens())
            {
                String n = t.nextToken();
                String u = t.nextToken();
                String pw = t.nextToken();
                String d_g = t.nextToken();
                int c_n = Integer.parseInt(t.nextToken());
                String e = t.nextToken();
                String c1 = t.nextToken();
                String c2 = t.nextToken();
                String ar = t.nextToken();
                String far = t.nextToken();
                if(ar.equalsIgnoreCase(location))
                {
                    t_a.add(new Tutor(n,u,pw,d_g,c_n,e,c1,c2,ar,far));
                }
            }
        }
        
        fr.close();
        br.close();
        }
        catch(IOException et)
                {
                   et.printStackTrace();
                }
  }
  public void Table_A()
  {
      t_a.removeAll(t_a);
      fillL_A(l_name);
      DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
      Object rowData[] = new Object[7];
      for(int i=0;i<t_a.size();i++)
      {
          rowData[0] = t_a.get(i).getN();
          rowData[1] = t_a.get(i).getC1();
          rowData[2] = t_a.get(i).getC2();
          rowData[3] = t_a.get(i).getC();
          rowData[4] = t_a.get(i).getEm();
          rowData[5] = t_a.get(i).getAd();
          rowData[6] = t_a.get(i).getFAd();
          model.addRow(rowData);
      }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
